// Package abs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package abs

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for LibraryMediaType.
const (
	LibraryMediaTypeBook    LibraryMediaType = "book"
	LibraryMediaTypePodcast LibraryMediaType = "podcast"
)

// Valid indicates whether the value is a known member of the LibraryMediaType enum.
func (e LibraryMediaType) Valid() bool {
	switch e {
	case LibraryMediaTypeBook:
		return true
	case LibraryMediaTypePodcast:
		return true
	default:
		return false
	}
}

// Defines values for LibraryItemMediaType.
const (
	LibraryItemMediaTypeBook    LibraryItemMediaType = "book"
	LibraryItemMediaTypePodcast LibraryItemMediaType = "podcast"
)

// Valid indicates whether the value is a known member of the LibraryItemMediaType enum.
func (e LibraryItemMediaType) Valid() bool {
	switch e {
	case LibraryItemMediaTypeBook:
		return true
	case LibraryItemMediaTypePodcast:
		return true
	default:
		return false
	}
}

// Defines values for ListLibraryItemsParamsMinified.
const (
	ListLibraryItemsParamsMinifiedN0 ListLibraryItemsParamsMinified = "0"
	ListLibraryItemsParamsMinifiedN1 ListLibraryItemsParamsMinified = "1"
)

// Valid indicates whether the value is a known member of the ListLibraryItemsParamsMinified enum.
func (e ListLibraryItemsParamsMinified) Valid() bool {
	switch e {
	case ListLibraryItemsParamsMinifiedN0:
		return true
	case ListLibraryItemsParamsMinifiedN1:
		return true
	default:
		return false
	}
}

// Defines values for ListLibraryItemsParamsDesc.
const (
	ListLibraryItemsParamsDescN0 ListLibraryItemsParamsDesc = "0"
	ListLibraryItemsParamsDescN1 ListLibraryItemsParamsDesc = "1"
)

// Valid indicates whether the value is a known member of the ListLibraryItemsParamsDesc enum.
func (e ListLibraryItemsParamsDesc) Valid() bool {
	switch e {
	case ListLibraryItemsParamsDescN0:
		return true
	case ListLibraryItemsParamsDescN1:
		return true
	default:
		return false
	}
}

// Defines values for ListLibraryItemsParamsCollapseseries.
const (
	N0 ListLibraryItemsParamsCollapseseries = "0"
	N1 ListLibraryItemsParamsCollapseseries = "1"
)

// Valid indicates whether the value is a known member of the ListLibraryItemsParamsCollapseseries enum.
func (e ListLibraryItemsParamsCollapseseries) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	default:
		return false
	}
}

// AuthorRef defines model for AuthorRef.
type AuthorRef struct {
	// Id Omit to create-or-match by name.
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

// BookMetadata The 'minified' metadata shape returned by /libraries/{id}/items?minified=1.
type BookMetadata struct {
	Asin *string `json:"asin,omitempty"`

	// AuthorName Joined "First, Second" string — minified shape only.
	AuthorName           *string                `json:"authorName,omitempty"`
	Description          *string                `json:"description,omitempty"`
	Explicit             *bool                  `json:"explicit,omitempty"`
	Genres               *[]string              `json:"genres,omitempty"`
	Isbn                 *string                `json:"isbn,omitempty"`
	Language             *string                `json:"language,omitempty"`
	NarratorName         *string                `json:"narratorName,omitempty"`
	PublishedDate        *string                `json:"publishedDate,omitempty"`
	PublishedYear        *string                `json:"publishedYear,omitempty"`
	Publisher            *string                `json:"publisher,omitempty"`
	SeriesName           *string                `json:"seriesName,omitempty"`
	Subtitle             *string                `json:"subtitle,omitempty"`
	Title                *string                `json:"title,omitempty"`
	TitleIgnorePrefix    *string                `json:"titleIgnorePrefix,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Folder defines model for Folder.
type Folder struct {
	FullPath             string                 `json:"fullPath"`
	Id                   string                 `json:"id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Library defines model for Library.
type Library struct {
	Folders              []Folder               `json:"folders"`
	Id                   string                 `json:"id"`
	MediaType            LibraryMediaType       `json:"mediaType"`
	Name                 string                 `json:"name"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LibraryMediaType defines model for Library.MediaType.
type LibraryMediaType string

// LibraryItem Minified shape. Many more fields exist in the un-minified shape
// (libraryFiles, audioFiles, chapters, etc.) — we don't need them.
type LibraryItem struct {
	AddedAt     *int    `json:"addedAt,omitempty"`
	BirthtimeMs *int    `json:"birthtimeMs,omitempty"`
	CtimeMs     *int    `json:"ctimeMs,omitempty"`
	FolderId    *string `json:"folderId,omitempty"`
	Id          string  `json:"id"`
	Ino         *string `json:"ino,omitempty"`
	IsFile      *bool   `json:"isFile,omitempty"`
	IsInvalid   *bool   `json:"isInvalid,omitempty"`
	IsMissing   *bool   `json:"isMissing,omitempty"`
	LibraryId   *string `json:"libraryId,omitempty"`

	// Media For books in minified mode, `metadata` is populated; full files
	// listings are omitted.
	Media                Media                  `json:"media"`
	MediaType            LibraryItemMediaType   `json:"mediaType"`
	MtimeMs              *int                   `json:"mtimeMs,omitempty"`
	Path                 *string                `json:"path,omitempty"`
	RelPath              *string                `json:"relPath,omitempty"`
	UpdatedAt            *int                   `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LibraryItemMediaType defines model for LibraryItem.MediaType.
type LibraryItemMediaType string

// LibraryItemsPage defines model for LibraryItemsPage.
type LibraryItemsPage struct {
	Collapseseries       *bool                  `json:"collapseseries,omitempty"`
	FilterBy             *string                `json:"filterBy,omitempty"`
	Include              *string                `json:"include,omitempty"`
	Limit                int                    `json:"limit"`
	MediaType            *string                `json:"mediaType,omitempty"`
	Minified             *bool                  `json:"minified,omitempty"`
	Offset               *int                   `json:"offset,omitempty"`
	Page                 int                    `json:"page"`
	Results              []LibraryItem          `json:"results"`
	SortBy               *string                `json:"sortBy,omitempty"`
	SortDesc             *bool                  `json:"sortDesc,omitempty"`
	Total                int                    `json:"total"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Media For books in minified mode, `metadata` is populated; full files
// listings are omitted.
type Media struct {
	CoverPath *string `json:"coverPath,omitempty"`
	Id        *string `json:"id,omitempty"`

	// Metadata The 'minified' metadata shape returned by /libraries/{id}/items?minified=1.
	Metadata             *BookMetadata          `json:"metadata,omitempty"`
	Tags                 *[]string              `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SearchHitBook defines model for SearchHitBook.
type SearchHitBook struct {
	// LibraryItem Minified shape. Many more fields exist in the un-minified shape
	// (libraryFiles, audioFiles, chapters, etc.) — we don't need them.
	LibraryItem LibraryItem `json:"libraryItem"`

	// MatchKey e.g. "title", "subtitle", "authors", "narrators"
	MatchKey             *string                `json:"matchKey,omitempty"`
	MatchText            *string                `json:"matchText,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Authors              *[]map[string]interface{} `json:"authors,omitempty"`
	Book                 *[]SearchHitBook          `json:"book,omitempty"`
	Narrators            *[]map[string]interface{} `json:"narrators,omitempty"`
	Podcast              *[]map[string]interface{} `json:"podcast,omitempty"`
	Series               *[]map[string]interface{} `json:"series,omitempty"`
	Tags                 *[]string                 `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}    `json:"-"`
}

// SeriesRef defines model for SeriesRef.
type SeriesRef struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name"`

	// Sequence String — supports "1", "1.5", "0.5".
	Sequence *string `json:"sequence,omitempty"`
}

// UpdateMediaMetadata Full metadata payload. Array fields (`authors`, `narrators`, `series`,
// `genres`) are REPLACED, not merged — always send a complete set.
type UpdateMediaMetadata struct {
	Asin        *string      `json:"asin,omitempty"`
	Authors     *[]AuthorRef `json:"authors,omitempty"`
	Description *string      `json:"description,omitempty"`
	Explicit    *bool        `json:"explicit,omitempty"`
	Genres      *[]string    `json:"genres,omitempty"`
	Isbn        *string      `json:"isbn,omitempty"`
	Language    *string      `json:"language,omitempty"`
	Narrators   *[]string    `json:"narrators,omitempty"`

	// PublishedYear String, not integer.
	PublishedYear *string      `json:"publishedYear,omitempty"`
	Publisher     *string      `json:"publisher,omitempty"`
	Series        *[]SeriesRef `json:"series,omitempty"`
	Subtitle      *string      `json:"subtitle,omitempty"`
	Title         *string      `json:"title,omitempty"`
}

// UpdateMediaRequest defines model for UpdateMediaRequest.
type UpdateMediaRequest struct {
	// Metadata Full metadata payload. Array fields (`authors`, `narrators`, `series`,
	// `genres`) are REPLACED, not merged — always send a complete set.
	Metadata             *UpdateMediaMetadata   `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// User ABS user object. We only use `id`, `username`, and `isAdmin`/permissions
// for diagnostics; many other fields exist.
type User struct {
	Id          *string           `json:"id,omitempty"`
	IsAdmin     *bool             `json:"isAdmin,omitempty"`
	Permissions *User_Permissions `json:"permissions,omitempty"`

	// Type e.g. "root", "admin", "user"
	Type                 *string                `json:"type,omitempty"`
	Username             *string                `json:"username,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// User_Permissions defines model for User.Permissions.
type User_Permissions struct {
	Upload               *bool                  `json:"upload,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ItemId defines model for ItemId.
type ItemId = string

// LibraryId defines model for LibraryId.
type LibraryId = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// SetItemCoverJSONBody defines parameters for SetItemCover.
type SetItemCoverJSONBody struct {
	// Url Public URL ABS will fetch the cover from.
	Url string `json:"url"`
}

// SetItemCoverMultipartBody defines parameters for SetItemCover.
type SetItemCoverMultipartBody struct {
	Cover openapi_types.File `json:"cover"`
}

// SetItemCover200JSONResponseBody defines parameters for SetItemCover.
type SetItemCover200JSONResponseBody struct {
	// Cover Path to the saved cover file on the server.
	Cover                *string                `json:"cover,omitempty"`
	Success              bool                   `json:"success"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// UpdateItemMedia200JSONResponseBody defines parameters for UpdateItemMedia.
type UpdateItemMedia200JSONResponseBody struct {
	// LibraryItem Minified shape. Many more fields exist in the un-minified shape
	// (libraryFiles, audioFiles, chapters, etc.) — we don't need them.
	LibraryItem          *LibraryItem           `json:"libraryItem,omitempty"`
	Updated              bool                   `json:"updated"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ListLibraries200JSONResponseBody defines parameters for ListLibraries.
type ListLibraries200JSONResponseBody struct {
	Libraries            []Library              `json:"libraries"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ListLibraryItemsParams defines parameters for ListLibraryItems.
type ListLibraryItemsParams struct {
	// Page 0-indexed page number.
	Page     *int                            `form:"page,omitempty" json:"page,omitempty"`
	Limit    *int                            `form:"limit,omitempty" json:"limit,omitempty"`
	Minified *ListLibraryItemsParamsMinified `form:"minified,omitempty" json:"minified,omitempty"`
	Sort     *string                         `form:"sort,omitempty" json:"sort,omitempty"`
	Desc     *ListLibraryItemsParamsDesc     `form:"desc,omitempty" json:"desc,omitempty"`

	// Filter Base64-encoded filter expression (e.g. `authors.<base64-id>`).
	Filter         *string                               `form:"filter,omitempty" json:"filter,omitempty"`
	Collapseseries *ListLibraryItemsParamsCollapseseries `form:"collapseseries,omitempty" json:"collapseseries,omitempty"`
	Include        *string                               `form:"include,omitempty" json:"include,omitempty"`
}

// ListLibraryItemsParamsMinified defines parameters for ListLibraryItems.
type ListLibraryItemsParamsMinified string

// ListLibraryItemsParamsDesc defines parameters for ListLibraryItems.
type ListLibraryItemsParamsDesc string

// ListLibraryItemsParamsCollapseseries defines parameters for ListLibraryItems.
type ListLibraryItemsParamsCollapseseries string

// SearchLibraryParams defines parameters for SearchLibrary.
type SearchLibraryParams struct {
	Q     string `form:"q" json:"q"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadItemMultipartBody defines parameters for UploadItem.
type UploadItemMultipartBody struct {
	Author    *string              `json:"author,omitempty"`
	Files     []openapi_types.File `json:"files"`
	FolderId  string               `json:"folderId"`
	LibraryId string               `json:"libraryId"`
	Series    *string              `json:"series,omitempty"`
	Title     string               `json:"title"`
}

// SetItemCoverJSONRequestBody defines body for SetItemCover for application/json ContentType.
type SetItemCoverJSONRequestBody SetItemCoverJSONBody

// SetItemCoverMultipartRequestBody defines body for SetItemCover for multipart/form-data ContentType.
type SetItemCoverMultipartRequestBody SetItemCoverMultipartBody

// UpdateItemMediaJSONRequestBody defines body for UpdateItemMedia for application/json ContentType.
type UpdateItemMediaJSONRequestBody = UpdateMediaRequest

// UploadItemMultipartRequestBody defines body for UploadItem for multipart/form-data ContentType.
type UploadItemMultipartRequestBody UploadItemMultipartBody

// Getter for additional properties for BookMetadata. Returns the specified
// element and whether it was found
func (a BookMetadata) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for BookMetadata
func (a *BookMetadata) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for BookMetadata to handle AdditionalProperties
func (a *BookMetadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["asin"]; found {
		err = json.Unmarshal(raw, &a.Asin)
		if err != nil {
			return fmt.Errorf("error reading 'asin': %w", err)
		}
		delete(object, "asin")
	}

	if raw, found := object["authorName"]; found {
		err = json.Unmarshal(raw, &a.AuthorName)
		if err != nil {
			return fmt.Errorf("error reading 'authorName': %w", err)
		}
		delete(object, "authorName")
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &a.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
		delete(object, "description")
	}

	if raw, found := object["explicit"]; found {
		err = json.Unmarshal(raw, &a.Explicit)
		if err != nil {
			return fmt.Errorf("error reading 'explicit': %w", err)
		}
		delete(object, "explicit")
	}

	if raw, found := object["genres"]; found {
		err = json.Unmarshal(raw, &a.Genres)
		if err != nil {
			return fmt.Errorf("error reading 'genres': %w", err)
		}
		delete(object, "genres")
	}

	if raw, found := object["isbn"]; found {
		err = json.Unmarshal(raw, &a.Isbn)
		if err != nil {
			return fmt.Errorf("error reading 'isbn': %w", err)
		}
		delete(object, "isbn")
	}

	if raw, found := object["language"]; found {
		err = json.Unmarshal(raw, &a.Language)
		if err != nil {
			return fmt.Errorf("error reading 'language': %w", err)
		}
		delete(object, "language")
	}

	if raw, found := object["narratorName"]; found {
		err = json.Unmarshal(raw, &a.NarratorName)
		if err != nil {
			return fmt.Errorf("error reading 'narratorName': %w", err)
		}
		delete(object, "narratorName")
	}

	if raw, found := object["publishedDate"]; found {
		err = json.Unmarshal(raw, &a.PublishedDate)
		if err != nil {
			return fmt.Errorf("error reading 'publishedDate': %w", err)
		}
		delete(object, "publishedDate")
	}

	if raw, found := object["publishedYear"]; found {
		err = json.Unmarshal(raw, &a.PublishedYear)
		if err != nil {
			return fmt.Errorf("error reading 'publishedYear': %w", err)
		}
		delete(object, "publishedYear")
	}

	if raw, found := object["publisher"]; found {
		err = json.Unmarshal(raw, &a.Publisher)
		if err != nil {
			return fmt.Errorf("error reading 'publisher': %w", err)
		}
		delete(object, "publisher")
	}

	if raw, found := object["seriesName"]; found {
		err = json.Unmarshal(raw, &a.SeriesName)
		if err != nil {
			return fmt.Errorf("error reading 'seriesName': %w", err)
		}
		delete(object, "seriesName")
	}

	if raw, found := object["subtitle"]; found {
		err = json.Unmarshal(raw, &a.Subtitle)
		if err != nil {
			return fmt.Errorf("error reading 'subtitle': %w", err)
		}
		delete(object, "subtitle")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["titleIgnorePrefix"]; found {
		err = json.Unmarshal(raw, &a.TitleIgnorePrefix)
		if err != nil {
			return fmt.Errorf("error reading 'titleIgnorePrefix': %w", err)
		}
		delete(object, "titleIgnorePrefix")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for BookMetadata to handle AdditionalProperties
func (a BookMetadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Asin != nil {
		object["asin"], err = json.Marshal(a.Asin)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'asin': %w", err)
		}
	}

	if a.AuthorName != nil {
		object["authorName"], err = json.Marshal(a.AuthorName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'authorName': %w", err)
		}
	}

	if a.Description != nil {
		object["description"], err = json.Marshal(a.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	if a.Explicit != nil {
		object["explicit"], err = json.Marshal(a.Explicit)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'explicit': %w", err)
		}
	}

	if a.Genres != nil {
		object["genres"], err = json.Marshal(a.Genres)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'genres': %w", err)
		}
	}

	if a.Isbn != nil {
		object["isbn"], err = json.Marshal(a.Isbn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isbn': %w", err)
		}
	}

	if a.Language != nil {
		object["language"], err = json.Marshal(a.Language)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'language': %w", err)
		}
	}

	if a.NarratorName != nil {
		object["narratorName"], err = json.Marshal(a.NarratorName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'narratorName': %w", err)
		}
	}

	if a.PublishedDate != nil {
		object["publishedDate"], err = json.Marshal(a.PublishedDate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'publishedDate': %w", err)
		}
	}

	if a.PublishedYear != nil {
		object["publishedYear"], err = json.Marshal(a.PublishedYear)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'publishedYear': %w", err)
		}
	}

	if a.Publisher != nil {
		object["publisher"], err = json.Marshal(a.Publisher)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'publisher': %w", err)
		}
	}

	if a.SeriesName != nil {
		object["seriesName"], err = json.Marshal(a.SeriesName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'seriesName': %w", err)
		}
	}

	if a.Subtitle != nil {
		object["subtitle"], err = json.Marshal(a.Subtitle)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subtitle': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.TitleIgnorePrefix != nil {
		object["titleIgnorePrefix"], err = json.Marshal(a.TitleIgnorePrefix)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'titleIgnorePrefix': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Folder. Returns the specified
// element and whether it was found
func (a Folder) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Folder
func (a *Folder) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Folder to handle AdditionalProperties
func (a *Folder) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fullPath"]; found {
		err = json.Unmarshal(raw, &a.FullPath)
		if err != nil {
			return fmt.Errorf("error reading 'fullPath': %w", err)
		}
		delete(object, "fullPath")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Folder to handle AdditionalProperties
func (a Folder) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["fullPath"], err = json.Marshal(a.FullPath)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'fullPath': %w", err)
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Library. Returns the specified
// element and whether it was found
func (a Library) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Library
func (a *Library) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Library to handle AdditionalProperties
func (a *Library) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["folders"]; found {
		err = json.Unmarshal(raw, &a.Folders)
		if err != nil {
			return fmt.Errorf("error reading 'folders': %w", err)
		}
		delete(object, "folders")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["mediaType"]; found {
		err = json.Unmarshal(raw, &a.MediaType)
		if err != nil {
			return fmt.Errorf("error reading 'mediaType': %w", err)
		}
		delete(object, "mediaType")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Library to handle AdditionalProperties
func (a Library) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Folders != nil {
		object["folders"], err = json.Marshal(a.Folders)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'folders': %w", err)
		}
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["mediaType"], err = json.Marshal(a.MediaType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mediaType': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LibraryItem. Returns the specified
// element and whether it was found
func (a LibraryItem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LibraryItem
func (a *LibraryItem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LibraryItem to handle AdditionalProperties
func (a *LibraryItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["addedAt"]; found {
		err = json.Unmarshal(raw, &a.AddedAt)
		if err != nil {
			return fmt.Errorf("error reading 'addedAt': %w", err)
		}
		delete(object, "addedAt")
	}

	if raw, found := object["birthtimeMs"]; found {
		err = json.Unmarshal(raw, &a.BirthtimeMs)
		if err != nil {
			return fmt.Errorf("error reading 'birthtimeMs': %w", err)
		}
		delete(object, "birthtimeMs")
	}

	if raw, found := object["ctimeMs"]; found {
		err = json.Unmarshal(raw, &a.CtimeMs)
		if err != nil {
			return fmt.Errorf("error reading 'ctimeMs': %w", err)
		}
		delete(object, "ctimeMs")
	}

	if raw, found := object["folderId"]; found {
		err = json.Unmarshal(raw, &a.FolderId)
		if err != nil {
			return fmt.Errorf("error reading 'folderId': %w", err)
		}
		delete(object, "folderId")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["ino"]; found {
		err = json.Unmarshal(raw, &a.Ino)
		if err != nil {
			return fmt.Errorf("error reading 'ino': %w", err)
		}
		delete(object, "ino")
	}

	if raw, found := object["isFile"]; found {
		err = json.Unmarshal(raw, &a.IsFile)
		if err != nil {
			return fmt.Errorf("error reading 'isFile': %w", err)
		}
		delete(object, "isFile")
	}

	if raw, found := object["isInvalid"]; found {
		err = json.Unmarshal(raw, &a.IsInvalid)
		if err != nil {
			return fmt.Errorf("error reading 'isInvalid': %w", err)
		}
		delete(object, "isInvalid")
	}

	if raw, found := object["isMissing"]; found {
		err = json.Unmarshal(raw, &a.IsMissing)
		if err != nil {
			return fmt.Errorf("error reading 'isMissing': %w", err)
		}
		delete(object, "isMissing")
	}

	if raw, found := object["libraryId"]; found {
		err = json.Unmarshal(raw, &a.LibraryId)
		if err != nil {
			return fmt.Errorf("error reading 'libraryId': %w", err)
		}
		delete(object, "libraryId")
	}

	if raw, found := object["media"]; found {
		err = json.Unmarshal(raw, &a.Media)
		if err != nil {
			return fmt.Errorf("error reading 'media': %w", err)
		}
		delete(object, "media")
	}

	if raw, found := object["mediaType"]; found {
		err = json.Unmarshal(raw, &a.MediaType)
		if err != nil {
			return fmt.Errorf("error reading 'mediaType': %w", err)
		}
		delete(object, "mediaType")
	}

	if raw, found := object["mtimeMs"]; found {
		err = json.Unmarshal(raw, &a.MtimeMs)
		if err != nil {
			return fmt.Errorf("error reading 'mtimeMs': %w", err)
		}
		delete(object, "mtimeMs")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["relPath"]; found {
		err = json.Unmarshal(raw, &a.RelPath)
		if err != nil {
			return fmt.Errorf("error reading 'relPath': %w", err)
		}
		delete(object, "relPath")
	}

	if raw, found := object["updatedAt"]; found {
		err = json.Unmarshal(raw, &a.UpdatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'updatedAt': %w", err)
		}
		delete(object, "updatedAt")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LibraryItem to handle AdditionalProperties
func (a LibraryItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AddedAt != nil {
		object["addedAt"], err = json.Marshal(a.AddedAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'addedAt': %w", err)
		}
	}

	if a.BirthtimeMs != nil {
		object["birthtimeMs"], err = json.Marshal(a.BirthtimeMs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'birthtimeMs': %w", err)
		}
	}

	if a.CtimeMs != nil {
		object["ctimeMs"], err = json.Marshal(a.CtimeMs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ctimeMs': %w", err)
		}
	}

	if a.FolderId != nil {
		object["folderId"], err = json.Marshal(a.FolderId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'folderId': %w", err)
		}
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.Ino != nil {
		object["ino"], err = json.Marshal(a.Ino)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ino': %w", err)
		}
	}

	if a.IsFile != nil {
		object["isFile"], err = json.Marshal(a.IsFile)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isFile': %w", err)
		}
	}

	if a.IsInvalid != nil {
		object["isInvalid"], err = json.Marshal(a.IsInvalid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isInvalid': %w", err)
		}
	}

	if a.IsMissing != nil {
		object["isMissing"], err = json.Marshal(a.IsMissing)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isMissing': %w", err)
		}
	}

	if a.LibraryId != nil {
		object["libraryId"], err = json.Marshal(a.LibraryId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'libraryId': %w", err)
		}
	}

	object["media"], err = json.Marshal(a.Media)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'media': %w", err)
	}

	object["mediaType"], err = json.Marshal(a.MediaType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mediaType': %w", err)
	}

	if a.MtimeMs != nil {
		object["mtimeMs"], err = json.Marshal(a.MtimeMs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mtimeMs': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.RelPath != nil {
		object["relPath"], err = json.Marshal(a.RelPath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relPath': %w", err)
		}
	}

	if a.UpdatedAt != nil {
		object["updatedAt"], err = json.Marshal(a.UpdatedAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'updatedAt': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LibraryItemsPage. Returns the specified
// element and whether it was found
func (a LibraryItemsPage) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LibraryItemsPage
func (a *LibraryItemsPage) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LibraryItemsPage to handle AdditionalProperties
func (a *LibraryItemsPage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["collapseseries"]; found {
		err = json.Unmarshal(raw, &a.Collapseseries)
		if err != nil {
			return fmt.Errorf("error reading 'collapseseries': %w", err)
		}
		delete(object, "collapseseries")
	}

	if raw, found := object["filterBy"]; found {
		err = json.Unmarshal(raw, &a.FilterBy)
		if err != nil {
			return fmt.Errorf("error reading 'filterBy': %w", err)
		}
		delete(object, "filterBy")
	}

	if raw, found := object["include"]; found {
		err = json.Unmarshal(raw, &a.Include)
		if err != nil {
			return fmt.Errorf("error reading 'include': %w", err)
		}
		delete(object, "include")
	}

	if raw, found := object["limit"]; found {
		err = json.Unmarshal(raw, &a.Limit)
		if err != nil {
			return fmt.Errorf("error reading 'limit': %w", err)
		}
		delete(object, "limit")
	}

	if raw, found := object["mediaType"]; found {
		err = json.Unmarshal(raw, &a.MediaType)
		if err != nil {
			return fmt.Errorf("error reading 'mediaType': %w", err)
		}
		delete(object, "mediaType")
	}

	if raw, found := object["minified"]; found {
		err = json.Unmarshal(raw, &a.Minified)
		if err != nil {
			return fmt.Errorf("error reading 'minified': %w", err)
		}
		delete(object, "minified")
	}

	if raw, found := object["offset"]; found {
		err = json.Unmarshal(raw, &a.Offset)
		if err != nil {
			return fmt.Errorf("error reading 'offset': %w", err)
		}
		delete(object, "offset")
	}

	if raw, found := object["page"]; found {
		err = json.Unmarshal(raw, &a.Page)
		if err != nil {
			return fmt.Errorf("error reading 'page': %w", err)
		}
		delete(object, "page")
	}

	if raw, found := object["results"]; found {
		err = json.Unmarshal(raw, &a.Results)
		if err != nil {
			return fmt.Errorf("error reading 'results': %w", err)
		}
		delete(object, "results")
	}

	if raw, found := object["sortBy"]; found {
		err = json.Unmarshal(raw, &a.SortBy)
		if err != nil {
			return fmt.Errorf("error reading 'sortBy': %w", err)
		}
		delete(object, "sortBy")
	}

	if raw, found := object["sortDesc"]; found {
		err = json.Unmarshal(raw, &a.SortDesc)
		if err != nil {
			return fmt.Errorf("error reading 'sortDesc': %w", err)
		}
		delete(object, "sortDesc")
	}

	if raw, found := object["total"]; found {
		err = json.Unmarshal(raw, &a.Total)
		if err != nil {
			return fmt.Errorf("error reading 'total': %w", err)
		}
		delete(object, "total")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LibraryItemsPage to handle AdditionalProperties
func (a LibraryItemsPage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Collapseseries != nil {
		object["collapseseries"], err = json.Marshal(a.Collapseseries)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'collapseseries': %w", err)
		}
	}

	if a.FilterBy != nil {
		object["filterBy"], err = json.Marshal(a.FilterBy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'filterBy': %w", err)
		}
	}

	if a.Include != nil {
		object["include"], err = json.Marshal(a.Include)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'include': %w", err)
		}
	}

	object["limit"], err = json.Marshal(a.Limit)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'limit': %w", err)
	}

	if a.MediaType != nil {
		object["mediaType"], err = json.Marshal(a.MediaType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaType': %w", err)
		}
	}

	if a.Minified != nil {
		object["minified"], err = json.Marshal(a.Minified)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'minified': %w", err)
		}
	}

	if a.Offset != nil {
		object["offset"], err = json.Marshal(a.Offset)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'offset': %w", err)
		}
	}

	object["page"], err = json.Marshal(a.Page)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'page': %w", err)
	}

	if a.Results != nil {
		object["results"], err = json.Marshal(a.Results)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'results': %w", err)
		}
	}

	if a.SortBy != nil {
		object["sortBy"], err = json.Marshal(a.SortBy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sortBy': %w", err)
		}
	}

	if a.SortDesc != nil {
		object["sortDesc"], err = json.Marshal(a.SortDesc)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sortDesc': %w", err)
		}
	}

	object["total"], err = json.Marshal(a.Total)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'total': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Media. Returns the specified
// element and whether it was found
func (a Media) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Media
func (a *Media) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Media to handle AdditionalProperties
func (a *Media) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["coverPath"]; found {
		err = json.Unmarshal(raw, &a.CoverPath)
		if err != nil {
			return fmt.Errorf("error reading 'coverPath': %w", err)
		}
		delete(object, "coverPath")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &a.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
		delete(object, "tags")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Media to handle AdditionalProperties
func (a Media) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CoverPath != nil {
		object["coverPath"], err = json.Marshal(a.CoverPath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'coverPath': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.Tags != nil {
		object["tags"], err = json.Marshal(a.Tags)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tags': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SearchHitBook. Returns the specified
// element and whether it was found
func (a SearchHitBook) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SearchHitBook
func (a *SearchHitBook) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SearchHitBook to handle AdditionalProperties
func (a *SearchHitBook) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["libraryItem"]; found {
		err = json.Unmarshal(raw, &a.LibraryItem)
		if err != nil {
			return fmt.Errorf("error reading 'libraryItem': %w", err)
		}
		delete(object, "libraryItem")
	}

	if raw, found := object["matchKey"]; found {
		err = json.Unmarshal(raw, &a.MatchKey)
		if err != nil {
			return fmt.Errorf("error reading 'matchKey': %w", err)
		}
		delete(object, "matchKey")
	}

	if raw, found := object["matchText"]; found {
		err = json.Unmarshal(raw, &a.MatchText)
		if err != nil {
			return fmt.Errorf("error reading 'matchText': %w", err)
		}
		delete(object, "matchText")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SearchHitBook to handle AdditionalProperties
func (a SearchHitBook) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["libraryItem"], err = json.Marshal(a.LibraryItem)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'libraryItem': %w", err)
	}

	if a.MatchKey != nil {
		object["matchKey"], err = json.Marshal(a.MatchKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'matchKey': %w", err)
		}
	}

	if a.MatchText != nil {
		object["matchText"], err = json.Marshal(a.MatchText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'matchText': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SearchResponse. Returns the specified
// element and whether it was found
func (a SearchResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SearchResponse
func (a *SearchResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SearchResponse to handle AdditionalProperties
func (a *SearchResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["authors"]; found {
		err = json.Unmarshal(raw, &a.Authors)
		if err != nil {
			return fmt.Errorf("error reading 'authors': %w", err)
		}
		delete(object, "authors")
	}

	if raw, found := object["book"]; found {
		err = json.Unmarshal(raw, &a.Book)
		if err != nil {
			return fmt.Errorf("error reading 'book': %w", err)
		}
		delete(object, "book")
	}

	if raw, found := object["narrators"]; found {
		err = json.Unmarshal(raw, &a.Narrators)
		if err != nil {
			return fmt.Errorf("error reading 'narrators': %w", err)
		}
		delete(object, "narrators")
	}

	if raw, found := object["podcast"]; found {
		err = json.Unmarshal(raw, &a.Podcast)
		if err != nil {
			return fmt.Errorf("error reading 'podcast': %w", err)
		}
		delete(object, "podcast")
	}

	if raw, found := object["series"]; found {
		err = json.Unmarshal(raw, &a.Series)
		if err != nil {
			return fmt.Errorf("error reading 'series': %w", err)
		}
		delete(object, "series")
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &a.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
		delete(object, "tags")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SearchResponse to handle AdditionalProperties
func (a SearchResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Authors != nil {
		object["authors"], err = json.Marshal(a.Authors)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'authors': %w", err)
		}
	}

	if a.Book != nil {
		object["book"], err = json.Marshal(a.Book)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'book': %w", err)
		}
	}

	if a.Narrators != nil {
		object["narrators"], err = json.Marshal(a.Narrators)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'narrators': %w", err)
		}
	}

	if a.Podcast != nil {
		object["podcast"], err = json.Marshal(a.Podcast)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'podcast': %w", err)
		}
	}

	if a.Series != nil {
		object["series"], err = json.Marshal(a.Series)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'series': %w", err)
		}
	}

	if a.Tags != nil {
		object["tags"], err = json.Marshal(a.Tags)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tags': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for UpdateMediaRequest. Returns the specified
// element and whether it was found
func (a UpdateMediaRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UpdateMediaRequest
func (a *UpdateMediaRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UpdateMediaRequest to handle AdditionalProperties
func (a *UpdateMediaRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UpdateMediaRequest to handle AdditionalProperties
func (a UpdateMediaRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for User. Returns the specified
// element and whether it was found
func (a User) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for User
func (a *User) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for User to handle AdditionalProperties
func (a *User) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["isAdmin"]; found {
		err = json.Unmarshal(raw, &a.IsAdmin)
		if err != nil {
			return fmt.Errorf("error reading 'isAdmin': %w", err)
		}
		delete(object, "isAdmin")
	}

	if raw, found := object["permissions"]; found {
		err = json.Unmarshal(raw, &a.Permissions)
		if err != nil {
			return fmt.Errorf("error reading 'permissions': %w", err)
		}
		delete(object, "permissions")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &a.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for User to handle AdditionalProperties
func (a User) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.IsAdmin != nil {
		object["isAdmin"], err = json.Marshal(a.IsAdmin)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isAdmin': %w", err)
		}
	}

	if a.Permissions != nil {
		object["permissions"], err = json.Marshal(a.Permissions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'permissions': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	if a.Username != nil {
		object["username"], err = json.Marshal(a.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for User_Permissions. Returns the specified
// element and whether it was found
func (a User_Permissions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for User_Permissions
func (a *User_Permissions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for User_Permissions to handle AdditionalProperties
func (a *User_Permissions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["upload"]; found {
		err = json.Unmarshal(raw, &a.Upload)
		if err != nil {
			return fmt.Errorf("error reading 'upload': %w", err)
		}
		delete(object, "upload")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for User_Permissions to handle AdditionalProperties
func (a User_Permissions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Upload != nil {
		object["upload"], err = json.Marshal(a.Upload)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'upload': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SetItemCover200JSONResponseBody. Returns the specified
// element and whether it was found
func (a SetItemCover200JSONResponseBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SetItemCover200JSONResponseBody
func (a *SetItemCover200JSONResponseBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SetItemCover200JSONResponseBody to handle AdditionalProperties
func (a *SetItemCover200JSONResponseBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cover"]; found {
		err = json.Unmarshal(raw, &a.Cover)
		if err != nil {
			return fmt.Errorf("error reading 'cover': %w", err)
		}
		delete(object, "cover")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SetItemCover200JSONResponseBody to handle AdditionalProperties
func (a SetItemCover200JSONResponseBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Cover != nil {
		object["cover"], err = json.Marshal(a.Cover)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cover': %w", err)
		}
	}

	object["success"], err = json.Marshal(a.Success)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'success': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for UpdateItemMedia200JSONResponseBody. Returns the specified
// element and whether it was found
func (a UpdateItemMedia200JSONResponseBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UpdateItemMedia200JSONResponseBody
func (a *UpdateItemMedia200JSONResponseBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UpdateItemMedia200JSONResponseBody to handle AdditionalProperties
func (a *UpdateItemMedia200JSONResponseBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["libraryItem"]; found {
		err = json.Unmarshal(raw, &a.LibraryItem)
		if err != nil {
			return fmt.Errorf("error reading 'libraryItem': %w", err)
		}
		delete(object, "libraryItem")
	}

	if raw, found := object["updated"]; found {
		err = json.Unmarshal(raw, &a.Updated)
		if err != nil {
			return fmt.Errorf("error reading 'updated': %w", err)
		}
		delete(object, "updated")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UpdateItemMedia200JSONResponseBody to handle AdditionalProperties
func (a UpdateItemMedia200JSONResponseBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.LibraryItem != nil {
		object["libraryItem"], err = json.Marshal(a.LibraryItem)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'libraryItem': %w", err)
		}
	}

	object["updated"], err = json.Marshal(a.Updated)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'updated': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListLibraries200JSONResponseBody. Returns the specified
// element and whether it was found
func (a ListLibraries200JSONResponseBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListLibraries200JSONResponseBody
func (a *ListLibraries200JSONResponseBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListLibraries200JSONResponseBody to handle AdditionalProperties
func (a *ListLibraries200JSONResponseBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["libraries"]; found {
		err = json.Unmarshal(raw, &a.Libraries)
		if err != nil {
			return fmt.Errorf("error reading 'libraries': %w", err)
		}
		delete(object, "libraries")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListLibraries200JSONResponseBody to handle AdditionalProperties
func (a ListLibraries200JSONResponseBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Libraries != nil {
		object["libraries"], err = json.Marshal(a.Libraries)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'libraries': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SetItemCoverWithBody request with any body
	SetItemCoverWithBody(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetItemCover(ctx context.Context, itemId ItemId, body SetItemCoverJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateItemMediaWithBody request with any body
	UpdateItemMediaWithBody(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateItemMedia(ctx context.Context, itemId ItemId, body UpdateItemMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListLibraries request
	ListLibraries(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListLibraryItems request
	ListLibraryItems(ctx context.Context, libraryId LibraryId, params *ListLibraryItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchLibrary request
	SearchLibrary(ctx context.Context, libraryId LibraryId, params *SearchLibraryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMe request
	GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadItemWithBody request with any body
	UploadItemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SetItemCoverWithBody(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetItemCoverRequestWithBody(c.Server, itemId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetItemCover(ctx context.Context, itemId ItemId, body SetItemCoverJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetItemCoverRequest(c.Server, itemId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateItemMediaWithBody(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateItemMediaRequestWithBody(c.Server, itemId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateItemMedia(ctx context.Context, itemId ItemId, body UpdateItemMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateItemMediaRequest(c.Server, itemId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListLibraries(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListLibrariesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListLibraryItems(ctx context.Context, libraryId LibraryId, params *ListLibraryItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListLibraryItemsRequest(c.Server, libraryId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchLibrary(ctx context.Context, libraryId LibraryId, params *SearchLibraryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchLibraryRequest(c.Server, libraryId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadItemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadItemRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSetItemCoverRequest calls the generic SetItemCover builder with application/json body
func NewSetItemCoverRequest(server string, itemId ItemId, body SetItemCoverJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetItemCoverRequestWithBody(server, itemId, "application/json", bodyReader)
}

// NewSetItemCoverRequestWithBody generates requests for SetItemCover with any type of body
func NewSetItemCoverRequestWithBody(server string, itemId ItemId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "itemId", itemId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/items/%s/cover", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateItemMediaRequest calls the generic UpdateItemMedia builder with application/json body
func NewUpdateItemMediaRequest(server string, itemId ItemId, body UpdateItemMediaJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateItemMediaRequestWithBody(server, itemId, "application/json", bodyReader)
}

// NewUpdateItemMediaRequestWithBody generates requests for UpdateItemMedia with any type of body
func NewUpdateItemMediaRequestWithBody(server string, itemId ItemId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "itemId", itemId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/items/%s/media", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListLibrariesRequest generates requests for ListLibraries
func NewListLibrariesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/libraries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListLibraryItemsRequest generates requests for ListLibraryItems
func NewListLibraryItemsRequest(server string, libraryId LibraryId, params *ListLibraryItemsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "libraryId", libraryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/libraries/%s/items", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Minified != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "minified", *params.Minified, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Desc != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "desc", *params.Desc, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Collapseseries != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "collapseseries", *params.Collapseseries, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Include != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "include", *params.Include, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchLibraryRequest generates requests for SearchLibrary
func NewSearchLibraryRequest(server string, libraryId LibraryId, params *SearchLibraryParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "libraryId", libraryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/libraries/%s/search", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMeRequest generates requests for GetMe
func NewGetMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadItemRequestWithBody generates requests for UploadItem with any type of body
func NewUploadItemRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/upload")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SetItemCoverWithBodyWithResponse request with any body
	SetItemCoverWithBodyWithResponse(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetItemCoverResponse, error)

	SetItemCoverWithResponse(ctx context.Context, itemId ItemId, body SetItemCoverJSONRequestBody, reqEditors ...RequestEditorFn) (*SetItemCoverResponse, error)

	// UpdateItemMediaWithBodyWithResponse request with any body
	UpdateItemMediaWithBodyWithResponse(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateItemMediaResponse, error)

	UpdateItemMediaWithResponse(ctx context.Context, itemId ItemId, body UpdateItemMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateItemMediaResponse, error)

	// ListLibrariesWithResponse request
	ListLibrariesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListLibrariesResponse, error)

	// ListLibraryItemsWithResponse request
	ListLibraryItemsWithResponse(ctx context.Context, libraryId LibraryId, params *ListLibraryItemsParams, reqEditors ...RequestEditorFn) (*ListLibraryItemsResponse, error)

	// SearchLibraryWithResponse request
	SearchLibraryWithResponse(ctx context.Context, libraryId LibraryId, params *SearchLibraryParams, reqEditors ...RequestEditorFn) (*SearchLibraryResponse, error)

	// GetMeWithResponse request
	GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResponse, error)

	// UploadItemWithBodyWithResponse request with any body
	UploadItemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadItemResponse, error)
}

type SetItemCoverResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SetItemCover200JSONResponseBody
}

// Status returns HTTPResponse.Status
func (r SetItemCoverResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetItemCoverResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SetItemCoverResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateItemMediaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UpdateItemMedia200JSONResponseBody
}

// Status returns HTTPResponse.Status
func (r UpdateItemMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateItemMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateItemMediaResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListLibrariesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListLibraries200JSONResponseBody
}

// Status returns HTTPResponse.Status
func (r ListLibrariesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListLibrariesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListLibrariesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListLibraryItemsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LibraryItemsPage
}

// Status returns HTTPResponse.Status
func (r ListLibraryItemsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListLibraryItemsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListLibraryItemsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchLibraryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchResponse
}

// Status returns HTTPResponse.Status
func (r SearchLibraryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchLibraryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchLibraryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UploadItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadItemResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SetItemCoverWithBodyWithResponse request with arbitrary body returning *SetItemCoverResponse
func (c *ClientWithResponses) SetItemCoverWithBodyWithResponse(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetItemCoverResponse, error) {
	rsp, err := c.SetItemCoverWithBody(ctx, itemId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetItemCoverResponse(rsp)
}

func (c *ClientWithResponses) SetItemCoverWithResponse(ctx context.Context, itemId ItemId, body SetItemCoverJSONRequestBody, reqEditors ...RequestEditorFn) (*SetItemCoverResponse, error) {
	rsp, err := c.SetItemCover(ctx, itemId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetItemCoverResponse(rsp)
}

// UpdateItemMediaWithBodyWithResponse request with arbitrary body returning *UpdateItemMediaResponse
func (c *ClientWithResponses) UpdateItemMediaWithBodyWithResponse(ctx context.Context, itemId ItemId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateItemMediaResponse, error) {
	rsp, err := c.UpdateItemMediaWithBody(ctx, itemId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateItemMediaResponse(rsp)
}

func (c *ClientWithResponses) UpdateItemMediaWithResponse(ctx context.Context, itemId ItemId, body UpdateItemMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateItemMediaResponse, error) {
	rsp, err := c.UpdateItemMedia(ctx, itemId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateItemMediaResponse(rsp)
}

// ListLibrariesWithResponse request returning *ListLibrariesResponse
func (c *ClientWithResponses) ListLibrariesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListLibrariesResponse, error) {
	rsp, err := c.ListLibraries(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListLibrariesResponse(rsp)
}

// ListLibraryItemsWithResponse request returning *ListLibraryItemsResponse
func (c *ClientWithResponses) ListLibraryItemsWithResponse(ctx context.Context, libraryId LibraryId, params *ListLibraryItemsParams, reqEditors ...RequestEditorFn) (*ListLibraryItemsResponse, error) {
	rsp, err := c.ListLibraryItems(ctx, libraryId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListLibraryItemsResponse(rsp)
}

// SearchLibraryWithResponse request returning *SearchLibraryResponse
func (c *ClientWithResponses) SearchLibraryWithResponse(ctx context.Context, libraryId LibraryId, params *SearchLibraryParams, reqEditors ...RequestEditorFn) (*SearchLibraryResponse, error) {
	rsp, err := c.SearchLibrary(ctx, libraryId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchLibraryResponse(rsp)
}

// GetMeWithResponse request returning *GetMeResponse
func (c *ClientWithResponses) GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResponse, error) {
	rsp, err := c.GetMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMeResponse(rsp)
}

// UploadItemWithBodyWithResponse request with arbitrary body returning *UploadItemResponse
func (c *ClientWithResponses) UploadItemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadItemResponse, error) {
	rsp, err := c.UploadItemWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadItemResponse(rsp)
}

// ParseSetItemCoverResponse parses an HTTP response from a SetItemCoverWithResponse call
func ParseSetItemCoverResponse(rsp *http.Response) (*SetItemCoverResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetItemCoverResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SetItemCover200JSONResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateItemMediaResponse parses an HTTP response from a UpdateItemMediaWithResponse call
func ParseUpdateItemMediaResponse(rsp *http.Response) (*UpdateItemMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateItemMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpdateItemMedia200JSONResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListLibrariesResponse parses an HTTP response from a ListLibrariesWithResponse call
func ParseListLibrariesResponse(rsp *http.Response) (*ListLibrariesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListLibrariesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListLibraries200JSONResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListLibraryItemsResponse parses an HTTP response from a ListLibraryItemsWithResponse call
func ParseListLibraryItemsResponse(rsp *http.Response) (*ListLibraryItemsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListLibraryItemsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LibraryItemsPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSearchLibraryResponse parses an HTTP response from a SearchLibraryWithResponse call
func ParseSearchLibraryResponse(rsp *http.Response) (*SearchLibraryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchLibraryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMeResponse parses an HTTP response from a GetMeWithResponse call
func ParseGetMeResponse(rsp *http.Response) (*GetMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUploadItemResponse parses an HTTP response from a UploadItemWithResponse call
func ParseUploadItemResponse(rsp *http.Response) (*UploadItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
